### ISSUE TITLE
Having trouble to install OpenSeaseis on Ubuntu 18.02 LTS

### ISSUE THREAD

**Issue by lewistgoss** [JohnWStockwellJr/OpenSeaSeis#11]
Having trouble to install OpenSeaseis on Ubuntu 18.02 LTS

**Comment by lewistgoss** [comment]
src/cs/geolib/methods_sampleInterpolation.cc: In function ‘void cseis_geolib::sincFunction(T)’:
src/cs/geolib/methods_sampleInterpolation.cc:239:12: error: return-statement with a value, in function returning 'void' [-fpermissive]
     return 1.0;
            ^~~
src/make/linux/Makefile_libs:184: recipe for target '/home/lewisgoss/opt/OpenSeaSeis-master/../lib_v2.05/obj/methods_sampleInterpolation.o' failed
make: *** [/home/lewisgoss/opt/OpenSeaSeis-master/../lib_v2.05/obj/methods_sampleInterpolation.o] Error 1
g++ -fPIC -shared -Wl,-soname,libsegy.so -o /home/lewisgoss/opt/OpenSeaSeis-master/../lib_v2.05/lib/libsegy.so /home/lewisgoss/opt/OpenSeaSeis-master/../lib_v2.05/obj/csSegyTraceHeader.o /home/lewisgoss/opt/OpenSeaSeis-master/../lib_v2.05/obj/csSegyHdrMap.o /home/lewisgoss/opt/OpenSeaSeis-master/../lib_v2.05/obj/csSegyWriter.o /home/lewisgoss/opt/OpenSeaSeis-master/../lib_v2.05/obj/csSegyBinHeader.o /home/lewisgoss/opt/OpenSeaSeis-master/../lib_v2.05/obj/csSegyReader.o -L/home/lewisgoss/opt/OpenSeaSeis-master/../lib_v2.05/lib -lgeolib -lc
/usr/bin/ld: cannot find -lgeolib

**Comment by lewistgoss** [comment]
I switched global flag from pedantic to permissive, seems to have helped and been necessary.

**Comment by lewistgoss** [comment]
OK, I got it to install using the permissive flat instead of pedantic.  However, when I try to run SeaView.sh, I get the following complaint:
Exception in thread "main" java.lang.NoClassDefFoundError: cseis/seaview/SeaView
Caused by: java.lang.ClassNotFoundException: cseis.seaview.SeaView
	at java.net.URLClassLoader$1.run(URLClassLoader.java:200)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:188)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:307)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:252)
	at java.lang.ClassLoader.loadClassInternal(ClassLoader.java:320)
Could not find the main class: cseis/seaview/SeaView.  Program will exit.
